# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2
final_space: true
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
  - type: prompt
    alignment: left
    newline: true
    enable_cursor_positioning: true
    segments:
      - type: path
        style: plain
        background: transparent
        foreground: p:blue
        template: "\n{{ .Path }}"
        properties:
          style: full

      - type: git
        style: plain
        foreground: "#6c6c6c"
        background: "transparent"
        template: " {{ .HEAD }} {{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<red>{{ if gt .Behind 0 }}⇣ {{ .Behind }}{{ end }}</><red>{{ if gt .Ahead 0 }}⇡{{ .Ahead }}{{ end }}</>"
        properties:
          style: full
          fetch_status: true
          commit_icon: "@"
          branch_icon: ""

  - type: prompt
    alignment: right
    segments:
      - type: executiontime
        style: powerline
        powerline_symbol: 
        foreground: "yellow"
        background: "transparent"
        template: " <#fefefe></> {{ .FormattedMs }}"
        properties:
          threshold: 500
          style: austin

  - type: prompt
    alignment: right
    segments:
      - type: sysinfo
        newline: true
        style: plain
        foreground: "yellow"
        background: "transparent"
        template: "  {{ round .PhysicalPercentUsed .Precision }}%"
        properties:
          precision: 0

  - type: prompt
    alignment: left
    segments:
      - type: text
        style: plain
        foreground_templates:
          - "{{if gt .Code 0}}red{{end}}"
          - "{{if eq .Code 0}}green{{end}}"
        background: transparent
        template: "⟩"
  - type: prompt
    alignment: left
    segments:
      - type: text
        style: plain
        template: "\n"

palette:
  blue: "#00ADEE"
